import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ROUTES from 'src/route';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>FuBon Bank Connect</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          FuBon Bank <a>Connect!</a>  
        </h1>

        <p className={styles.description}>
          design by dengliang
        </p>

        <div className={styles.grid}>
          <a href={ROUTES.workspace} className={styles.card}>
            <h2>Workspace &rarr;</h2>
            <p>Your chat client && Your All in one Notebook</p>
          </a>

          <a href={ROUTES.projectManage} className={styles.card}>
            <h2>Project Manage &rarr;</h2>
            <p>Vividly display the project status and Detail </p>
          </a>

          <a
            href={ROUTES.itJournal}
            className={styles.card}
          >
            <h2>IT Journal &rarr;</h2>
            <p>Summary and display of the latest technology of bank</p>
          </a>

          <a
            href={ROUTES.fbcash}
            className={styles.card}
          >
            <h2>FB cash &rarr;</h2>
            <p>
            A peer-to-peer cash system for the Bank of FuBon.
            </p>
          </a>

          <a
            href={ROUTES.board}
            className={styles.card}
          >
            <h2>Board &rarr;</h2>
            <p>
            Intra bank bulletin board and some news.
            </p>
          </a>
          <a
            href={ROUTES.template}
            className={styles.card}
          >
            <h2>Template &rarr;</h2>
            <p>
              global article or memo template for all users.
            </p>
          </a>
          <a
            href=""
            className={styles.card}
          >
            <h2>Chat &rarr;</h2>
            <p>
              Chat tool combined with template and fbcash.
            </p>
          </a> 
          {/* <a
            href=""
            className={styles.card}
          >
            <h2>Nebula AI &rarr;</h2>
            <p>
              A logic learning Artificial Intelligence implementation base on graph database.
            </p>
          </a> */}
          <a
            href=""
            className={styles.card}
          >
            <h2>Data Analysis &rarr;</h2>
            <p>
              some other useful tools such as data analysis.
            </p>
          </a>
          <a
            href=""
            className={styles.card}
          >
            <h2>Admin &rarr;</h2>
            <p>
              system administrator can manage users and settings.
            </p>
          </a>
          
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href=""
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
